version: '3.4'

services:
  nuxt3starter:
    image: nuxt3starter
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
